/**
 * Blog routes (all require X-Hub-Secret)
 * POST /api/blog/trigger           — start a blog run (internal AI pipeline)
 * POST /api/blog/reset             — reset stuck/failed run
 * GET  /api/blog/status            — current run status
 * POST /api/blog/queue/build       — store a 7-day content queue from Dashboard
 * POST /api/blog/queue/clear       — clear the content queue
 * POST /api/blog/queue/run-next    — trigger n8n WF1 with hub_callback_url,
 *                                    popping next keyword from queue if no keyword in body
 */

import * as crypto from "crypto";
import { Router, Request, Response, NextFunction } from "express";
import { BlogUseCase } from "@modules/blog/BlogUseCase";
import { StateManager } from "@modules/state/StateManager";
import { N8nWorkflowAdapter } from "@infra/n8n/N8nWorkflowAdapter";
import { ValidationError, ConflictError } from "@shared/errors";
import { generateRunId } from "@shared/id";
import { ContentQueueItem } from "@core/application/ports/IStateRepository";

export function createBlogRoutes(
  blogUseCase: BlogUseCase,
  stateManager: StateManager,
  n8n?: N8nWorkflowAdapter,
): Router {
  const router = Router();

  // POST /api/blog/trigger
  router.post("/trigger", async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const { keyword, language, categoryIds } = req.body as {
        keyword?: unknown;
        language?: unknown;
        categoryIds?: unknown;
      };

      if (!keyword || typeof keyword !== "string" || keyword.trim().length === 0) {
        throw new ValidationError("keyword is required and must be a non-empty string");
      }

      const result = await blogUseCase.trigger({
        keyword: keyword.trim(),
        language: typeof language === "string" ? language : "th",
        categoryIds: Array.isArray(categoryIds) ? (categoryIds as number[]) : [],
      });

      res.status(201).json({ ok: true, data: result });
    } catch (err) {
      next(err);
    }
  });

  // POST /api/blog/reset
  router.post("/reset", async (_req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      await blogUseCase.reset();
      res.json({ ok: true, data: { message: "Blog state reset to idle" } });
    } catch (err) {
      next(err);
    }
  });

  // GET /api/blog/status
  router.get("/status", async (_req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const state = await stateManager.get();
      res.json({ ok: true, data: state.blog });
    } catch (err) {
      next(err);
    }
  });

  // POST /api/blog/queue/build
  // Accepts an array of queue items from Dashboard (generated by generateQueueItems())
  // and stores them in Hub v2 state. Replaces any existing queue.
  router.post("/queue/build", async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const body = req.body as { items?: unknown };
      if (!Array.isArray(body.items) || body.items.length === 0) {
        throw new ValidationError("items must be a non-empty array");
      }

      // Validate + normalize each item
      const items: ContentQueueItem[] = (body.items as Record<string, unknown>[]).map((raw, idx) => {
        if (typeof raw.keyword !== "string" || !raw.keyword.trim()) {
          throw new ValidationError(`items[${idx}].keyword is required`);
        }
        if (typeof raw.category !== "number") {
          throw new ValidationError(`items[${idx}].category must be a number`);
        }
        return {
          id: typeof raw.id === "string" ? raw.id : `q-${Date.now()}-${idx}`,
          date: typeof raw.date === "string" ? raw.date : new Date().toISOString().slice(0, 10),
          keyword: raw.keyword.trim(),
          category: raw.category,
          visual_hint: typeof raw.visual_hint === "string" ? raw.visual_hint : "contemporary",
          status: "pending" as const,
          runId: null,
          postUrl: null,
        };
      });

      await stateManager.setContentQueue(items);
      // Return count at top level so Marketing.tsx toast (j.count) works
      res.json({ ok: true, count: items.length, data: { count: items.length } });
    } catch (err) {
      next(err);
    }
  });

  // POST /api/blog/queue/clear
  router.post("/queue/clear", async (_req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      await stateManager.clearContentQueue();
      res.json({ ok: true, data: { message: "Content queue cleared" } });
    } catch (err) {
      next(err);
    }
  });

  // POST /api/blog/queue/run-next
  // Priority order for keyword:
  //   1. Body has explicit keyword   → use it directly (manual override)
  //   2. No keyword in body          → pop next pending item from content_queue
  //   3. Queue is also empty         → keyword="" → n8n Topic Engine PRO picks randomly
  router.post("/queue/run-next", async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      if (!n8n) {
        res.status(503).json({ ok: false, error: "N8N_NOT_CONFIGURED: N8N_WEBHOOK_BASE_URL missing" });
        return;
      }

      // Guard: reject if already running
      const state = await stateManager.get();
      if (state.blog.status === "running") {
        throw new ConflictError(
          "BLOG_ALREADY_RUNNING",
          `Blog run already in progress: ${state.blog.runId ?? "unknown"}`,
        );
      }

      const body = req.body as { keyword?: string; category?: number; queue_item_id?: string };
      const runId = generateRunId();
      const secret = process.env.HUB_SECRET ?? "";
      const hubPublicBase = (process.env.HUB_PUBLIC_BASE_URL ?? "").replace(/\/$/, "");

      if (!hubPublicBase) {
        res.status(503).json({ ok: false, error: "HUB_PUBLIC_BASE_URL not configured" });
        return;
      }

      let keyword = body.keyword ?? "";
      let category = body.category ?? 13;
      let queue_item_id = body.queue_item_id ?? "";

      // If no keyword provided, try to pop the next item from the content queue
      if (!keyword) {
        const nextItem = await stateManager.popNextQueueItem(runId);
        if (nextItem) {
          keyword = nextItem.keyword;
          category = nextItem.category;
          queue_item_id = nextItem.id;
        }
        // If nextItem is null → queue empty → keyword stays "" → Topic Engine PRO handles it
      }

      // Generate HMAC token — validated by /webhook/n8n callback
      const token = crypto.createHmac("sha256", secret).update(runId).digest("hex");
      const hub_callback_url = `${hubPublicBase}/webhook/n8n?token=${token}`;

      // Mark blog as running in state
      await stateManager.setBlogRunning(runId, keyword || "auto");

      // Trigger n8n WF1 webhook with full payload
      await n8n.trigger("blog-run", {
        runId,
        hub_callback_url,
        keyword,
        category,
        queue_item_id,
      });

      res.json({ ok: true, data: { runId, hub_callback_url, keyword: keyword || "auto", queue_item_id } });
    } catch (err) {
      next(err);
    }
  });

  return router;
}
